name: JFrog Docker Publish

on:
  push:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: my-app
      JFROG_DOCKER_REPO: 418949-docker-local
      REGISTRY: hts2.jfrog.io

    steps:
      - uses: actions/checkout@v4

      - name: Setup JFrog CLI (OIDC)
        id: setup-jfrog-cli
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ secrets.JF_URL }}
          JFROG_CLI_OIDC_PROJECT_KEY: devops
        with:
          oidc-provider-name: harish
          oidc-audience: jfrog-github

      - name: Verify OIDC
        run: jf rt ping

      # IMPORTANT: use OIDC token manually
      - name: Docker Login (FIXED)
        run: |
          echo "${{ steps.setup-jfrog-cli.outputs.oidc-token }}" \
            | docker login ${REGISTRY} \
              -u "${{ steps.setup-jfrog-cli.outputs.oidc-user }}" \
              --password-stdin

      - name: Build Image
        run: |
          docker build -t ${IMAGE_NAME}:${{ github.sha }} .

      - name: Tag Image
        run: |
          docker tag ${IMAGE_NAME}:${{ github.sha }} \
            ${REGISTRY}/${JFROG_DOCKER_REPO}/${IMAGE_NAME}:${{ github.sha }}

      - name: Push Image
        run: |
          docker push ${REGISTRY}/${JFROG_DOCKER_REPO}/${IMAGE_NAME}:${{ github.sha }}

      - name: Publish Build Info
        run: |
          jf rt build-collect-env
          jf rt build-add-git
          jf rt build-publish
