name: JFrog Docker Publish

on:
  push:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: my-app
      # Subdomain registry from Artifactory "Set Me Up"
      REGISTRY: hts2-418949-docker-local.jfrog.io

    steps:
      - uses: actions/checkout@v4

      - name: Setup JFrog CLI (OIDC)
        id: setup
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ secrets.JF_URL }}
          #JFROG_CLI_OIDC_PROJECT_KEY: "devops"
        with:
          oidc-provider-name: ${{ secrets.OIDC_PROVIDER }}
          oidc-audience: ${{ secrets.ODIC_AUDIENCE }}

      - name: Verify login
        run: jf rt ping

      - name: Docker Login (OIDC)
        run: |
          echo "${{ steps.setup.outputs.oidc-token }}" | docker login $REGISTRY \
            -u "${{ steps.setup.outputs.oidc-user }}" \
            --password-stdin

      - name: Build
        run: docker build -t $REGISTRY/$IMAGE_NAME:${{ github.sha }} .

      - name: Push
        run: docker push $REGISTRY/$IMAGE_NAME:${{ github.sha }}
        
